### PR TITLE
Fix upcast -> downcast

### PR DESCRIPTION
**Pull request by danaugrs**
Should be "downcast" instead of "upcast".
Thanks for building Matchstick!

### CODE REVIEW

**Comment by georg-getz** [comment]
Hey, thanks for the PR. Although you are generally correct about upcasting being casting to a parent and downcasting being casting to a child, the reason we have left it as upcasting in the docs is because the common error people run into in their subgraphs is when they try to cast in the following way: `let newGravatarEvent = newMockEvent() as NewGravatar` which although technically downcasting throws the following error in AssemblyScript: `Mapping aborted with message: unexpected upcast`. And we want people to associate that part of the docs with this error.

**Comment by danaugrs** [comment]
Thanks for the explanation! Yeah, apparently AssemblyScript is making the original mistake.
I created an issue there (https://github.com/AssemblyScript/assemblyscript/issues/2422) and made a PR to fix it (https://github.com/AssemblyScript/assemblyscript/pull/2423).

**Comment by danaugrs** [comment]
The AssemblyScript compiler has been fixed, including the error message: https://github.com/AssemblyScript/assemblyscript/pull/2423.

**Comment by georg-getz** [comment]
> The AssemblyScript compiler has been fixed, including the error message: [AssemblyScript/assemblyscript#2423](https://github.com/AssemblyScript/assemblyscript/pull/2423).

 Great, the only thing remaining is that the new version with this fix crashes the wasm file compilation. I'll try to check it out next week.

**Comment by MaxGraey** [comment]
> Great, the only thing remaining is that the new version with this fix crashes the wasm file compilation

Do you have exported mutable globals in such wasm modules? Binaryen introduced new pass which has one minor issue with such globals. It will be fixed in new version of Binaryem:
https://github.com/AssemblyScript/assemblyscript/pull/2461

Also, make sure you're using >= 0.21.1 instead 0.21.0

**Comment by georg-getz** [comment]
I'm closing this PR 😐 The reason is because this change will only be helpful for people using AssemblyScript 0.20.x+ and as of now that doesn't seem like the direction the Graph is heading in. My guess is that unless something extremely useful or necessary for the Graph is added in future versions of AS, they will probably just stick to version 0.19.10.

The reason the version is such a big problem is that parts of `graph-ts` do not compile with the newer versions of AS which will force all subgraph developers to have their AS version be inherited from `graph-ts`.

Needless to say if they decide to update their AS version this change will be enacted.

Thanks for the PR again.

**Pull request closed without merging**
